# Only needed to preview the site on your own machine.
# GitHub Pages builds the site for you and ignores this file.
#
#   gem install bundler
#   bundle install
#   bundle exec jekyll serve --livereload
#
source "https://rubygems.org"

gem "jekyll", "~> 4.3"

# Ruby 3.4 dropped these from the standard library.
gem "csv"
gem "base64"
gem "bigdecimal"
gem "logger"
